name: deploy on push
on:
  push:
    branches:
    - main
jobs:
    deploy-app:
      runs-on: ubuntu-latest
      steps:
        - name: check out the code to build server
          uses: actions/checkout@v4
        - name: copy files to server
          uses: appleboy/scp-action@master
          with:
            host: ${{secrets.HOST}}
            username: ${{secrets.SSH_USER_NAME}}
            port: ${{secrets.SERVER_PORT}}
            key: ${{secrets.SERVER_SSH_KEY}}
            source: "./html/*"
            target: "/var/www/html"
            strip_components: 1
        